<?php
 // module/Album/view/projects/projects/delete.phtml:

 $title = 'Delete projects';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($projects->name); ?>' by
     '<?php echo $this->escapeHtml($projects->description); ?>'?
 </p>
 <?php
 $url = $this->url('projects', array(
     'action' => 'delete',
     'idproject'     => $this->idproject,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidprojectden" name="idproject" value="<?php echo (int) $projects->idproject; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>