<?php
 // module/Projects/view/projects/projects/index.phtml:

 $title = 'My projects';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('projects', array('controller'=>'index','action'=>'add'));?>">Add new projects</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Description</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($projects as $project) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($project->name);?></td>
     <td><?php echo $this->escapeHtml($project->description);?></td>
     <td>
         <a href="<?php echo $this->url('projects',
             array('action'=>'edit', 'idproject' => $project->idproject));?>">Edit</a>
         <a href="<?php echo $this->url('projects',
             array('action'=>'delete', 'idproject' => $project->idproject));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>